"""Vibe-Trading bridge plus lightweight local validation helpers."""

from __future__ import annotations

import json
import math
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tools.calculate_technical_analysis import load_rows

from .common import RESEARCH_ROOT, VIBE_SNAPSHOT_COMMIT, VIBE_VENDOR_ROOT, utc_now, write_json


@dataclass
class BacktestRequest:
    ticker: str
    strategy: str
    start: str
    end: str
    market: str = "a_share"
    source: str = "auto"
    interval: str = "1D"
    engine: str = "daily"


class VibeBacktestBridge:
    """Prepare and optionally run Vibe-Trading backtests from this workspace."""

    def __init__(self, run_root: Path | None = None, vendor_root: Path | None = None) -> None:
        self.run_root = run_root or RESEARCH_ROOT / "vibe_runs"
        self.vendor_root = vendor_root or VIBE_VENDOR_ROOT

    def prepare_run(self, request: BacktestRequest) -> dict[str, Any]:
        run_id = f"{request.ticker.replace('.', '_')}_{request.strategy}_{utc_now().replace(':', '').replace('+', '_')}"
        run_dir = self.run_root / run_id
        code_dir = run_dir / "code"
        code_dir.mkdir(parents=True, exist_ok=True)
        config = {
            "codes": [request.ticker],
            "start_date": request.start,
            "end_date": request.end,
            "source": request.source,
            "interval": request.interval,
            "engine": request.engine,
            "strategy": request.strategy,
            "validation": {
                "monte_carlo": True,
                "bootstrap_sharpe_ci": True,
                "walk_forward": True,
            },
        }
        write_json(run_dir / "config.json", config)
        (code_dir / "signal_engine.py").write_text(render_signal_engine(request.strategy), encoding="utf-8")
        return {
            "status": "prepared",
            "run_dir": str(run_dir),
            "config_path": str(run_dir / "config.json"),
            "signal_engine_path": str(code_dir / "signal_engine.py"),
            "vendor_snapshot": VIBE_SNAPSHOT_COMMIT,
            "upstream_source": "vendor/vibe-trading",
        }

    def run(self, run_dir: str | Path, timeout: int = 300) -> dict[str, Any]:
        agent_root = self.vendor_root / "agent"
        entry = agent_root / "backtest" / "runner.py"
        if not entry.exists():
            return {"status": "error", "error": f"Vibe runner not found: {entry}"}
        env = os.environ.copy()
        env.update({
            "VIBE_TRADING_ALLOWED_RUN_ROOTS": str(self.run_root),
            "PYTHONPATH": str(agent_root),
        })
        try:
            proc = subprocess.run(
                [sys.executable, "-m", "backtest.runner", str(run_dir)],
                cwd=str(agent_root),
                env={**env, **dict()},
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            return {"status": "error", "error": repr(exc), "run_dir": str(run_dir)}
        return {
            "status": "ok" if proc.returncode == 0 else "error",
            "exit_code": proc.returncode,
            "stdout_tail": proc.stdout[-2000:],
            "stderr_tail": proc.stderr[-2000:],
            "run_dir": str(run_dir),
        }


def render_signal_engine(strategy: str) -> str:
    lookback = 20 if strategy == "technical_breakout" else 10
    return "\n".join(
        [
            '"""Generated by trading_core for Vibe-Trading backtest bridge."""',
            f"LOOKBACK = {lookback}",
            "class SignalEngine:",
            "    def generate(self, data_map):",
            "        signals = {}",
            "        for code, frame in data_map.items():",
            "            close = frame['close'] if 'close' in frame else frame.iloc[:, 0]",
            "            rolling = close.rolling(LOOKBACK, min_periods=LOOKBACK).mean()",
            "            signal = (close > rolling).astype(float).fillna(0.0)",
            "            signals[code] = signal",
            "        return signals",
        ]
    ) + "\n"


def run_local_breakout_backtest(ohlcv_path: Path) -> dict[str, Any]:
    rows = load_rows(ohlcv_path)
    if len(rows) < 25:
        return {
            "status": "insufficient_data",
            "missing_data": ["Need at least 25 bars for local technical_breakout backtest."],
        }
    closes = [row["close"] for row in rows]
    positions: list[int] = []
    for index, close in enumerate(closes):
        if index < 20:
            positions.append(0)
            continue
        ma20 = sum(closes[index - 20 : index]) / 20
        positions.append(1 if close > ma20 else 0)
    returns: list[float] = []
    trades = 0
    previous_position = 0
    for index in range(1, len(closes)):
        position = positions[index - 1]
        returns.append(position * (closes[index] / closes[index - 1] - 1))
        if positions[index] != previous_position:
            trades += 1
        previous_position = positions[index]
    equity = [1.0]
    for ret in returns:
        equity.append(equity[-1] * (1 + ret))
    total_return = equity[-1] - 1
    max_dd = max_drawdown(equity)
    sharpe = annualized_sharpe(returns)
    wins = [ret for ret in returns if ret > 0]
    losses = [ret for ret in returns if ret < 0]
    return {
        "status": "ok",
        "engine": "trading_core_local_validation",
        "strategy": "technical_breakout",
        "bar_count": len(rows),
        "metrics": {
            "total_return": round(total_return, 6),
            "sharpe": sharpe,
            "max_drawdown": max_dd,
            "win_rate": round(len(wins) / (len(wins) + len(losses)), 4) if wins or losses else 0.0,
            "trade_count": trades,
        },
        "validation": {
            "monte_carlo": "not_run_local_lightweight",
            "bootstrap_sharpe_ci": "not_run_local_lightweight",
            "walk_forward": "not_run_local_lightweight",
        },
        "limitations": [
            "Local validation is a lightweight bridge check; run the Vibe engine for full execution modeling.",
            "No personal position sizing or return promise is produced.",
        ],
    }


def max_drawdown(equity: list[float]) -> float:
    peak = equity[0]
    drawdowns = []
    for value in equity:
        peak = max(peak, value)
        drawdowns.append(value / peak - 1 if peak else 0)
    return round(min(drawdowns), 6)


def annualized_sharpe(returns: list[float]) -> float | None:
    if len(returns) < 2:
        return None
    mean = sum(returns) / len(returns)
    variance = sum((ret - mean) ** 2 for ret in returns) / (len(returns) - 1)
    std = math.sqrt(variance)
    if std == 0:
        return None
    return round(mean / std * math.sqrt(252), 4)
